### PR TITLE
Calculator milestone 1

### PR DESCRIPTION
**Pull request by pipe2442**
The first milestone for the calculator project, all the basic structure for a react app was created and required dependencies were added. Deploy can be found on https://pipe2442.github.io/react-basic-calculator/

### CODE REVIEW

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 
@pipe2442 congratulations on this milestone Almost all the project requirement is met, I saw that your code is been reviewed but can't find the PR, please for your subsequent project. kindly use the same PR to ensure reviewer continuity and professionalism. thanks, however changes is required
### Highlights

- an app is initialized with create-react-app 👍🏻 
-  unnecessary files or assets, such as the React svg Logo, are deleted 👍🏻 
-  big.js was added to package.json. 👍🏻 
-  prop-types added to package.json  👍🏻 
-  the app runs correctly with npm start. 👍🏻 
-  app is deployed 👍🏻

### Improve 

- [x] Kindly update your Readme file with the Microverse Readme template and the live link is included in the README file.

### once specific changes are made kindly request for review

**Comment by pipe2442** [comment]
Thanks for your review the Readme file was updated.

**Review by peterrobert — CHANGES_REQUESTED** [review]
Hi @pipe2442 , 

Great work on this project 👏.  However, the change requested in the last review is still yet to be implemented. Kindly check below ⬇️ 

 ## Required Changes ♻️

- [ ] it will be great to update your readme file with the Microverse readme template. Also, provide a link to the live version of your application ⬇️ 
app-deployed


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------

**Comment by pipe2442** [comment]
Thanks for your review the Readme file was updated.

**Comment by bellom** [comment]
> Thanks for your review the Readme file was updated.

@pipe2442 You have done well with the README update but we are missing some needed information in the README file, if we check the [Microverse template](https://github.com/microverseinc/readme-template) you will see there is a section where you're supposed to add `Setup`.

In other words; we need to make sure your README file is descriptive enough, the minimum checklist for a descriptive README file includes the project title, project description, and instructions on how to set up and run the project.

Set up example:
```
- git clone `your repo`
- cd into the folder
- git checkout `branch-name`
- run `npm i`
- run `npm start`
```

I will stay online for few minutes so that you won't need to send in another CRR.

**Review by bellom — APPROVED** [review]
## Hi @pipe2442  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Pull request merged**
